# Generated by Django 5.1 on 2024-08-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('approximateTime', models.TimeField()),
                ('approximateCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('surname', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('taskPerDay', models.IntegerField()),
                ('startWorkDay', models.TimeField()),
                ('endWorkDay', models.TimeField()),
                ('rating', models.FloatField()),
                ('isHaveOurItems', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CleanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('whatCleanerDo', models.TextField()),
                ('pricePerHr', models.IntegerField()),
                ('amountOrders', models.IntegerField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('liveRoom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('corridor', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('washLiquidUsage', models.IntegerField()),
                ('employeeSalary', models.IntegerField()),
                ('marge', models.IntegerField()),
                ('amortisation', models.IntegerField()),
                ('transport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('description', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WashLiquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('totalClean', models.IntegerField()),
                ('basicClean', models.IntegerField()),
                ('supportClean', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inProcess', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=30)),
                ('startTask', models.TimeField()),
                ('endTask', models.TimeField()),
                ('breakTime', models.TimeField()),
                ('cleaningTime', models.TimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('isGood', models.BooleanField(default=True)),
                ('message', models.TextField(null=True)),
                ('approximateTime', models.TimeField()),
                ('approximatePrice', models.IntegerField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenLineApiv1.cleaner')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenLineApiv1.cleantype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenLineApiv1.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenLineApiv1.cleaner')),
            ],
        ),
    ]
