# Generated by Django 5.1 on 2024-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenLineApiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priceToPay',
            field=models.FloatField(null=True),
        ),
    ]
