# Generated by Django 5.1 on 2024-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenLineApiv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='2024-08-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
