# Generated by Django 5.1 on 2024-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenLineApiv1', '0002_order_date_alter_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='breakTime',
            field=models.TimeField(default='01:00'),
        ),
    ]
