# Generated by Django 5.1 on 2024-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenLineApiv1', '0003_alter_order_cleaningtime_alter_order_pricetopay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isGood',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
