# Generated by Django 5.1 on 2024-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenLineApiv1', '0004_alter_order_isgood_alter_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cleaningTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isGood',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceToPay',
            field=models.FloatField(blank=True),
        ),
    ]
